spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      username: configUser
      password: configPass
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8085
