spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
            - id: auth-security-service
              uri: lb://AUTH-SECURITY-SERVICE
              predicates:
                - Path=/api/auth/**

jwt:
  secret: 3Y8xV5+v9DqP3+7lTnHZR0X9p8ZXk6Y7RliA2FWq2BA=

  security:
    user:
      name: admin
      password: secret

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

